---
title: "DS-301-01-1_09_09_26"
format: html
editor: visual
---

## EDA for Comp Sci Plus One

## Loading Libraries

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(bayesrules)
library(ggpubr)
library(plotly)
library(report)
```

```{r}
df = read.csv("HT_2013-2025.csv")
```

## Plot 1

```{r}
#number of each sub offense
ggplot(data=df, aes(x = OFFENSE_SUBCAT_NAME, fill = ACTUAL_COUNT))+
geom_bar()

```

## Plot 2

```{r}
df %>%
  count(DATA_YEAR) %>%
  ggplot(aes(x = reorder(DATA_YEAR, -n), y = n)) +
  geom_col() +
  labs(x = "Year", y = "Count", title = "recorded incidents per year") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## Plot 3

```{r}
#number of reports in each state
df %>%
  count(STATE_NAME) %>%
  ggplot(aes(x = reorder(STATE_NAME, -n), y = n)) +
  geom_col() +
  labs(x = "State Name", y = "Count", title = "Frequency of State") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## Plot 4 - Subcategory

```{r}
# SUBCATEGORY -- stacked bar by year
df |> 
  group_by(DATA_YEAR, OFFENSE_SUBCAT_NAME) |> 
  summarise(offenses = sum(ACTUAL_COUNT), .groups = "drop") |> 
  ggplot(aes(x = factor(DATA_YEAR), y = offenses, fill = OFFENSE_SUBCAT_NAME)) +
  geom_col() +
  labs(title = "Offenses by year and subcategory",
       x = "Year", y = "Offenses", fill = "Subcategory") +
  theme_minimal() +
  theme(legend.position = "bottom")
```

## Analysis:

```{r}
state_df <- df %>% 
  group_by(STATE_ABBR, OFFENSE_SUBCAT_NAME) %>%
summarise(COUNT = sum(ACTUAL_COUNT), .groups = 'drop')
model <- lm(COUNT ~ OFFENSE_SUBCAT_NAME + STATE_ABBR, data = state_df)
summary(model)
```

```{r}
ggplot(state_df, aes(x = STATE_ABBR, y = COUNT, color = OFFENSE_SUBCAT_NAME)) +
  geom_jitter() +
  geom_smooth(method = "lm") +
  stat_cor()
```

```{r}
# 1. Prepare sample data
# Already using df #

levels(df$OFFENSE_SUBCAT_NAME)
class(df$OFFENSE_SUBCAT_NAME)

df$OFFENSE_SUBCAT_NAME_F <- as.factor(df$OFFENSE_SUBCAT_NAME)
class(df$OFFENSE_SUBCAT_NAME_F)
levels(df$OFFENSE_SUBCAT_NAME_F)

# 2. Fit the linear model
model <- lm(ACTUAL_COUNT ~ OFFENSE_SUBCAT_NAME, data = df)

# 3. View the regression coefficients and statistical summary
summary(model)


















```

```{r}
ggplot(df, aes(x = OFFENSE_SUBCAT_NAME, y = ACTUAL_COUNT)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_cor()

ggplot(df, aes(x = OFFENSE_SUBCAT_NAME, y = ACTUAL_COUNT)) +
  geom_boxplot() +
  geom_jitter(width = 0.2, alpha = 0.5) +
  geom_smooth(method = "lm") +
  stat_cor()
```
